serve:
  description: Load a static server with live reload and Vue component compilation.
  tasks:
    - browserify:serve
    - browserSync:serve

build:
  description: Generate distributable component code.
  tasks:
    - browserify:build
    - uglify:build

default:
  - serve
