serve:
  src: 'app.js'
  dest: 'js/app.js'
  options:
    transform: '<%= s.browserify.options.transform %>'
    watch: true

build:
  src: 'src/component.js'
  dest: 'dist/<%= s.componentName %>.js'
  options:
    transform: '<%= s.browserify.options.transform %>'
    plugin:
      - browserify-derequire
    exclude:
      - vue
      - vue-hot-reload-api
    browserifyOptions:
      standalone: '<%= s.componentName %>'
